config: Link libfontconfig when Xft is enabled
Xft pattern APIs resolve to FcPattern* entry points, so builds that
enable libXft also need fontconfig on the link line.

Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11349,6 +11349,73 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
+  # Xft fontconfig patterns (FcPattern*) need libfontconfig at link time.
+  if test "x$cv_libXft" = "xyes"; then
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for library containing FcPatternCreate" >&5
+printf %s "checking for library containing FcPatternCreate... " >&6; }
+if test ${ac_cv_search_FcPatternCreate+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  ac_func_search_save_LIBS=$LIBS
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+char FcPatternCreate ();
+int
+main (void)
+{
+return FcPatternCreate ();
+  ;
+  return 0;
+}
+_ACEOF
+for ac_lib in '' fontconfig
+do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  if ac_fn_c_try_link "$LINENO"
+then :
+  ac_cv_search_FcPatternCreate=$ac_res
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam \
+    conftest$ac_exeext
+  if test ${ac_cv_search_FcPatternCreate+y}
+then :
+  break
+fi
+done
+if test ${ac_cv_search_FcPatternCreate+y}
+then :
+
+else $as_nop
+  ac_cv_search_FcPatternCreate=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_search_FcPatternCreate" >&5
+printf "%s\n" "$ac_cv_search_FcPatternCreate" >&6; }
+ac_res=$ac_cv_search_FcPatternCreate
+if test "$ac_res" != no
+then :
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
+else $as_nop
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: libfontconfig not found; Xft may fail to link" >&5
+printf "%s\n" "$as_me: WARNING: libfontconfig not found; Xft may fail to link" >&2;}
+fi
+
+  fi
+
+
 fi
 
 
